config/routes.rb
Store::Application.routes.draw do
  get "info/about"
  resources :products
  root to: 'products#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
  after_update :flush_name_cache

  def flush_name_cache
    Rails.cache.delete([:category, id, :name]) if name_changed?
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :name, :price, :released_on, :category_id
  belongs_to :category
  
  def category_name
    Rails.cache.fetch([:category, category_id, :name], expires_in: 5.minutes) do
      category.name
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <div id="container">
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/products/index.html.erb
<h1>Products</h1>

<table id="products">
  <tr>
    <th>Product Name</th>
    <th>Category</th>
    <th>Release Date</th>
    <th>Price</th>
  </tr>
<% @products.each do |product| %>
  <tr>
    <td><%= link_to(product.name, product) %></td>
    <td><%= product.category_name %></td>
    <td><%= product.released_on.strftime("%B %e, %Y") %></td>
    <td><%= number_to_currency(product.price) %></td>
  </tr>
<% end %>
</table>

app/views/products/show.html.erb
<h1><%= @product.name %></h1>

<p>
  <b>Price:</b>
  <%= number_to_currency @product.price %>
</p>

<p>
  <b>Category:</b>
  <%= @product.category_name %>
</p>

<p><%= link_to "Back to Products", products_path %></p>